### ISSUE TITLE
Low Disk Space notification

### ISSUE THREAD

**Issue by markshank** [mszoek/airyx#106]
After leaving 0.3.0pre2 Live CD run overnight, this appears:

![Low Disk Space 2021-09-05 071741](https://user-images.githubusercontent.com/25345979/132124950-850839c5-b671-4755-8754-7011c644dfe1.png)

**Comment by probonopd** [comment]
Check size of your log and/or swap files.

**Comment by markshank** [comment]
I clicked the "Open in File Manager" button and the notification disappeared, but nothing else appeared.  So I selected Go/Home from the menu bar.  Filer reports plenty of space in the bottom right corner of its window:

![Filer 2021-09-05 073232](https://user-images.githubusercontent.com/25345979/132125423-95df45c0-f834-4b1b-ad44-af69ffd3fc0a.png)

**Comment by markshank** [comment]
> Check size of your log and/or swap files.

I tried to open a terminal from the Tool menu, but it would not display.  Had to switch to the text console for this:

![Free space 2021-09-05 080548](https://user-images.githubusercontent.com/25345979/132126288-57c3d184-63bb-481a-99eb-c3bf3cdccc2a.png)

![Logs 2021-09-05 082034](https://user-images.githubusercontent.com/25345979/132126584-2d4a3101-9af2-437e-b0d2-263b8ba2a7aa.png)

**Comment by mszoek** [comment]
> I clicked the "Open in File Manager" button and the notification disappeared, but nothing else appeared.

That may be KDE trying to open it in Dolphin. It should be configured to use Filer but perhaps that is not quite working.

**Comment by mszoek** [comment]
> > Check size of your log and/or swap files.
> 
> I tried to open a terminal from the Tool menu, but it would not display. Had to switch to the text console for this:

Interesting - that works for me. Combined with your other issue, it makes me wonder if I have missed checking in a config file somewhere. Could you please split this and the "Open in file manager" problem to separate issues so I don't lose track of them?

**Comment by mszoek** [comment]
I'll leave mine running today while I'm out and see if I can spot where the usage is. Thanks as always for your awesome testing and bug hunting!

**Comment by markshank** [comment]
> Interesting - that works for me. Combined with your other issue, it makes me wonder if I have missed checking in a config file somewhere.

I would speculate that the lack of disk resource makes it difficult to launch anything.

**Comment by markshank** [comment]
> I'll leave mine running today while I'm out and see if I can spot where the usage is.

The Proxmox Summary page for this VM shows a bump in memory usage starting at 3:00 am.  Some sort of scheduled housekeeping?

![Memory Usage 2021-09-05 134447](https://user-images.githubusercontent.com/25345979/132136481-83c72774-5261-4da2-93db-f768addd0da3.png)

**Comment by markshank** [comment]
> Some sort of scheduled housekeeping?

Bingo!  The smoking gun:

![cron periodic daily 2021-09-06 061223](https://user-images.githubusercontent.com/25345979/132201731-8af72a9a-5109-443f-834f-2859ec5f3db0.png)

**Comment by markshank** [comment]
Supporting evidence:

![tail messages 2021-09-06 063121](https://user-images.githubusercontent.com/25345979/132204014-3efdd169-f43c-4ab8-9740-b1c0724efc1c.png)

**Comment by markshank** [comment]
Not sure how much effort you want to expend trying to fix this issue or the related issues.

"Doctor, Airyx Live CD runs out of disk space when I leave it running overnight."

Doctor:  "Don't let it run overnight."

**Comment by mszoek** [comment]
Nice work! The culprit seems to be the `pkg check -qsa` command run by `/etc/periodic/security/460.pkg-checksum` as part of the daily cron jobs. The problem is easily reproducible by running that command, but I am still trying to figure out exactly where the data is being written.

> Not sure how much effort you want to expend trying to fix this issue or the related issues.

I'm wondering exactly that myself :) My intent for the LiveCD is mainly to provide a nice graphical installer and rescue environment, and a short-term preview of the OS for the curious. I did not really expect it to run more than a few hours - but this is ugly and I would like to fix it. Since this is a ramdisk, perhaps we don't really need to run these cron jobs at all and that would neatly get around it.

**Comment by mszoek** [comment]
I couldn't resist looking into this more and I think I understand what is happening now. Calculating checksums on all the package files seems to cause a shadow file for each file to be created in the upper (ramdisk) layer of the unionfs. This results in the ramdisk filling up. 

Anyway, going to disable cron on the live CD for now.

**Comment by markshank** [comment]
I was trying to make sense out of the "df -h" output.  I'm guessing unionfs is combining the read-only furybsd zpool on CD with the memdisk ramdisk?  All writes would happen in memdisk.  So updating a bunch of existing files on the CD would result in copies being written to memdisk?

**Comment by mszoek** [comment]
Worked around for 0.3.0pre3 and won't (can't) fix properly.

**Comment by mszoek** [comment]
> I was trying to make sense out of the "df -h" output.  I'm guessing unionfs is combining the read-only furybsd zpool on CD with the memdisk ramdisk?  All writes would happen in memdisk.  So updating a bunch of existing files on the CD would result in copies being written to memdisk?

Yes! That's exactly how it works :)
