### ISSUE TITLE
Unable to open Terminal from Filer Tool menu

### ISSUE THREAD

**Issue by markshank** [mszoek/airyx#107]
> > Check size of your log and/or swap files.
> 
> I tried to open a terminal from the Tool menu, but it would not display. Had to switch to the text console for this:

Interesting - that works for me. Combined with your other issue, it makes me wonder if I have missed checking in a config file somewhere. Could you please split this and the "Open in file manager" problem to separate issues so I don't lose track of them?

**Note:  The system was disk constrained when this issue was observed**

_Originally posted by @mszoek in https://github.com/mszoek/airyx/issues/106#issuecomment-913163289_

**Comment by mszoek** [comment]
Have you been able to open a terminal from the Tools menu when the system is not constrained?

**Comment by markshank** [comment]
Yes, that works as expected.

**Comment by mszoek** [comment]
OK, perfect! Thanks for double-checking :) Sounds like you were right about the cause being no disk space!
