### ISSUE TITLE
Error - "Operation not supported" dialog displayed when Go/Trash from Desktop menu

### ISSUE THREAD

**Issue by markshank** [mszoek/airyx#111]
1.  Right-click created empty file on desktop.
2.  Right-click file and move to trash.
3.  Select Go/Trash from menu.
4. Trash folder is displayed, followed by error dialog.
5. Don't see trashed file in Trash.

![Trash Error 2021-09-08 130143](https://user-images.githubusercontent.com/25345979/132560673-9fc7eaf3-b2df-49b4-b786-d087ba14c09e.png)

**Comment by probonopd** [comment]
Fwiw, wuickly tested this on my locally installed helloSystem, seems to work here.

**Comment by mszoek** [comment]
Confirmed. Also seen on "Network". I suspect this is because Airyx does not have gio or gvfs installed yet to handle those URIs.

**Comment by mszoek** [comment]
No longer using this Filer app, closing.
