### ISSUE TITLE
Filer: quirky behavior not consistent with settings

### ISSUE THREAD

**Issue by mszoek** [mszoek/airyx#116]
Filer has some interesting behavior inconsistent with its settings file.
- One click activation of items when double click is expected (`SingleClick=false`)
- Opening new windows when navigating to a new folder when Spatial Mode is off (`SpatialMode=false`)
  - But not when using Up or Back icons or opening a sidebar location

Why???

**Comment by markshank** [comment]
When I click on the tree icon in the system menu and select System Preferences, I get a Quick Settings page with a conflicting setting.  Does this override Filer settings?

![Sys Pref 2021-09-15 081303](https://user-images.githubusercontent.com/25345979/133431599-54e46e65-aa25-471b-8ae3-3bb329b44100.png)

**Comment by markshank** [comment]
Just tried changing the setting to "Selects them" and the Filer behavior changes to what you were expecting.

**Comment by markshank** [comment]
Couldn't find a setting for "Spatial Mode".  Maybe the KDE file app has settings?

**Comment by mszoek** [comment]
Consider my mind = blown. Those are KDE's preferences which I assumed would not apply to Filer since it is not a KDE app. Nice work!

**Comment by markshank** [comment]
I noticed the difference in Filer behavior between HelloSystem & Airyx early on.  When I discovered that KDE preference, I assumed you had wired it that way to make a point that this is not HelloSystem.  Imagine my surprise when you asked "Why?".

Now I echo;  Why???  Is it a D-Bus thing?

**Comment by mszoek** [comment]
Hah! I should have asked earlier :)

**Comment by mszoek** [comment]
No longer using KDE or Filer, closing.
