### ISSUE TITLE
furybsd-install of 0.3.0pre2 iso on UEFI fails with umount error

### ISSUE THREAD

**Issue by markshank** [mszoek/airyx#127]
Issue occurs on QEMU OVMF (UEFI).  Not an issue when installed on QEMU SeaBios.

![UEFI furybsd-install 2021-09-20 055802](https://user-images.githubusercontent.com/25345979/133985170-a6222bf7-2b70-45ca-a832-4a20e54d1e54.png)
.

**Comment by mszoek** [comment]
The new `Install airyxOS.app` should work much better (I hope). It requires UEFI and supports both SCSI and SATA/IDE devices. Please give that a shot after I get the new release posted!

**Comment by grahamperrin** [comment]
> requires UEFI

If not UEFI, then will installation not complete? Or are there post-installation consequences?

**Comment by mszoek** [comment]
It will complete but the installer currently only creates a GPT + EFI boot configuration. It's still very rough - no compatibility checks, no legacy boot, minimal error checking, English only. But functional enough to start playing with it.

**Comment by markshank** [comment]
> The new `Install airyxOS.app` should work much better (I hope). It requires UEFI and supports both SCSI and SATA/IDE devices. Please give that a shot after I get the new release posted!

SCSI works for me now.  That lets me use the paravirtual SCSI controller to get better I/O performance on my virtual disk.  I did have a little problem with UEFI, but that was due to Proxmox 7.1 defaulting to Secure Boot for Microsoft support.  I turned that off and it worked great!

**Comment by mszoek** [comment]
AWESOME! 🎉 Thanks for checking that! I will close this issue now that we have a new installer.
