### ISSUE TITLE
Kate opens existing file without displaying existing text

### ISSUE THREAD

**Issue by markshank** [mszoek/airyx#129]
This may be premature, but I thought I'd report it anyway.

1. Use Filer to Go to Applications and open Kate
2. Type some text into Kate and save file onto Desktop
3. Close Kate
4. Right click on saved file on Desktop and select Open
5. Kate opens with saved file name displayed, but without any text from file
6. Select File/Save from menu and following error is displayed;

![Kate open error 2021-09-24 073641](https://user-images.githubusercontent.com/25345979/134668281-cb300841-91fe-4958-901a-5ebfce695918.png)

**Comment by mszoek** [comment]
Yep, I know about this one. KDE (or at least Kate) does not like file URLs with a host part (i.e. `file://localhost/path/to/file`). I put code in `open` to convert them to `file:///path/to/file` but I need to move that into LaunchServices so that it works with Filer and everything else.
