### ISSUE TITLE
Install FreeBSD.app: does not launch

### ISSUE THREAD

**Issue by grahamperrin** [mszoek/airyx#135]
Airyx_0.3.0pre2_f12_amd64.iso … so this is probably not a bug, in the context of it being explicitly incomplete and alpha quality. 

Using Filer to open the application has no visible effect. 

A terminal view of things: 

![image](https://user-images.githubusercontent.com/192271/135715569-c517c509-d82e-411c-8420-dfd02d5521ca.png)

– is that attempt to run, at the command line, sane?

**Comment by grahamperrin** [comment]
Sorry, I only just discovered the discussions area. From <https://github.com/mszoek/airyx/discussions/94#discussioncomment-1236707>: 

> … I'll try to get the installer fixed up …

**Comment by mszoek** [comment]
Just to close the loop here, I suspect your permissions error might be due to `/tmp` being mode `0755` instead of mode `1777` which is noted in bug #125. It's on my list for 0.3.0.

**Comment by grahamperrin** [comment]
Thanks, and FYI the change of mode is not a workaround. Looking forward to the 0.3.0 and so on :-)

**Comment by mszoek** [comment]
Good to know! Hmm...
