### ISSUE TITLE
Rounded RAM value

### ISSUE THREAD

**Issue by Synaelle** [mszoek/airyx#180]
I think the RAM value is rounded a bit too much, it's a VM with 4096MB and it show to me 5GB
Something is wrong here

![image](https://user-images.githubusercontent.com/29670037/151001154-1636a88f-0587-4fa0-b15d-6b40cec26266.png)

**Comment by mszoek** [comment]
LOL, thanks! I'll fix that :)

**Comment by mszoek** [comment]
@Synaelle can you please capture the actual RAM as reported by FreeBSD with:
`sysctl hw | grep 'mem:'`

**Comment by LucasG42** [comment]
Hello, I created some VM's each one with  4096 MB (4GB), 4505 MB (4.4 GB), 4608 MB (4.5 GB), 4710 MB (4.6 GB). Only in the last two cases this issue appear. 

-- FreeBSD 12.0 on QEMU

**Comment by mszoek** [comment]
Thanks for testing! That would make sense and seems like appropriate rounding up in that case. I wonder if the OP's VM actually had 4906 MB instead of 4096 MB? Anyway, I will add a decimal place in the display for odd cases like VMs.

**Comment by Synaelle** [comment]
![image](https://user-images.githubusercontent.com/29670037/151459556-b3eb41a5-ec14-48c7-a94e-28bf490cb54b.png)
Definitely not 4906MB, here's the command result: 
![image](https://user-images.githubusercontent.com/29670037/151459909-195aaf24-6b8b-4264-8d23-532f011ab3fc.png)

**Comment by LucasG42** [comment]
@Synaelle  converting the result bellow (return a number of bytes) in GigaBytes you get something like:

Phys: 4236816384 bytes = 3.94 GB
User: 3884171264 bytes = 3.61 GB
Real: 4831838208 bytes = 4.5  GB

the real memory is greater or equal to 4.5, in most of rounding  functions .5 > round up

**Comment by mszoek** [comment]
Weird! 4096 MB should be 4294967296 bytes (4096 * 1024 * 1024). Not sure why it returns a different number in VirtualBox, but it looks like our math is right. The number shown is `realmem / (1024 * 1024 * 1024)` as an integer. I'll add the decimal place so it shows more accurately as 4.5.
