### ISSUE TITLE
Installation doesn't create a bootable disk

### ISSUE THREAD

**Issue by darkoverlordofdata** [mszoek/airyx#211]
Live user works great. But after installing, I don't have a bootable system. This system works fine with GhostBSD and helloSystem; in fact I just installed helloSystem over the unbootable airyx, and it is working just fine. I have a Dell Inspiron 3521. It's a 2nd generation i3, and FreeBSD doesn't work from UEFI, it only works when I set bios to legacy node

**Comment by mszoek** [comment]
If you installed using the `Install airyxOS.app`, it only creates a UEFI/GPT boot disk at present. The `Install FreeBSD.app` will create both (but has other problems) so I left it there until the new installer is finished. Would that account for what you saw?

**Comment by darkoverlordofdata** [comment]
yes, I was using the install airyxoss.app. I can wait until it is further along, I just wanted ti see if it was working yet. Thanks, looks nice.

**Comment by darkoverlordofdata** [comment]
I tried the Install FreeBSD.app - that doesn't create a bootable disk either. The only difference is there is no error message, it just displays a black screen ans does nothing.

**Comment by mszoek** [comment]
Hmm. strange. Quite a few people have installed from that image on various real and virtual machines. It does require UEFI and 64-bit CPU but should be OK as long as you have that.
What was the error message on boot?

**Comment by darkoverlordofdata** [comment]
I have UEFI, but it's an older version that is not compatible with FreeBSD. I can only boot in legcy mode, but that isn't working for airyx. It works fine with GhostBSD, helloSystem, FuryBSD, and vanilla FrreeBSD. But not with Airyx.

**Comment by mszoek** [comment]
OK, that makes sense. I haven't spent much time on legacy boot support. A few people have asked for it now for older machines so I'll see what can be done there. Thanks for the update!

**Comment by darkoverlordofdata** [comment]
Are there any plans on supporting ARM? I've given up on intel, they only last 2-3 years; except for the old Dell relics. My 2 newer computers are both ARM.

**Comment by mszoek** [comment]
Eventually, yes - I just don't have time or hardware for it currently. This is an area that someone could take on.

**Comment by darkoverlordofdata** [comment]
Great, I'll wait and see what the future brings. In the meantime, helloSystem is quite adequate. I'm sure you are busy, so I'll stop taking up your time!

**Comment by flavio20002** [comment]
It is better to reopen it, until there is an iso with the working installer...

Same issue:

- Install airyx.app doesn't boot up
- Install FreeBSD.app only show splash screen after boot up and then shows a black screen.

**Comment by mszoek** [comment]
So you booted the live CD, used `Install airyxOS.app` to write the system to a disk, booted the system from that disk? And you just get a black screen?

**Comment by flavio20002** [comment]
Booted the live CD, used **Install airyx.app**, restarted -> No boot
Booted the live CD, used **Install FreeBSD.app**, restarted -> Seen the splash screen, then black screen with mouse pointer

**Comment by mszoek** [comment]
What is the system hardware and is it set up for UEFI boot?

In the second case, is there a menu bar at the top of the screen or no?

**Comment by mszoek** [comment]
There is an intermittent bug with the `Install FreeBSD` app which has been fixed in `Install airyxOS`, but `Install airyxOS` only creates EFI/GPT boot stuff and `Install FreeBSD` creates both that and legacy boot loader. That is the reason `Install FreeBSD` is still present.

If you are hitting this bug, you get a black screen with no menu bar and a mouse cursor. It can be fixed by switching to a console with Ctrl+Alt+F2, logging in and executing `sudo chmod 1777 /tmp` then `sudo /etc/rc.d/slim restart`. That should fix the permissions preventing X from creating its run socket and restart the X server. If that does not help, it may be a different issue.

**Comment by flavio20002** [comment]
I'm using Virtualbox, configured for Freebsd (no EFI). This is what I see after installing with **Install FreeBSD.app** and rebooted. Maybe I've done someting wrong? Anyway, the live CD works perfectly, I can use it.

![image](https://user-images.githubusercontent.com/10809301/152656908-3cfc532d-2df1-4b51-813d-ffd46d062926.png)

**Comment by mszoek** [comment]
Try the `chmod` fix above and let me know...

**Comment by flavio20002** [comment]
Works! It is worth write it into the README?

**Comment by mszoek** [comment]
Probably should go in the Troubleshooting part of the FAQ somewhere or on the wiki.

**Comment by darkoverlordofdata** [comment]
I tried installing again,  to try the chmod hack. But it all worked this time. same media, so I'm guessing its intermittent.  Other than no internet, the only things I see are are the time is on the wrong timezone - EST but should be PST, so 3 hrs late, and it's based in FreeBSD 12. Many fresh ports have only binaries for 13 and 14.

**Comment by mszoek** [comment]
Cool! Yep, the black screen bug has been intermittent and hard to track down. Glad you got it working!
The upcoming 0.4.0 is based on FreeBSD 13.0-STABLE and the latest 2022Q1 ports.
