### ISSUE TITLE
Tanuki Download Fails all the time

### ISSUE THREAD

**Issue by shashankhacker730** [mszoek/airyx#227]
Download link for Tanuki version in Releases section is faulty. It always fails with HTTP Error 401/403/404 in between. Please fix this.

**Comment by agam778** [comment]
The server hosting the ISOs is offline right now while it moves hosting services. Will hopefully back up by tomorrow.

**Comment by mszoek** [comment]
This one? https://github.com/mszoek/airyx/releases/download/airyx-0.3.0/Airyx_0.3.0_f12_amd64.iso.zip

It is hosted by GitHub so no idea what might be happening there.

**Comment by mszoek** [comment]
Has been downloaded several times since this report - no issues reported. Closing.
