### ISSUE TITLE
Choose reasonable default fonts

### ISSUE THREAD

**Issue by mszoek** [mszoek/airyx#23]
Choose reasonable default fonts in Onyx2D/O2Font.m initialize(). Make sure these fonts are installed in the base image. Update BASEFONT defined in framework.common.mk.

**Comment by mszoek** [comment]
Remember to update AppKit/X11.subproj/O2Font_FT.m lines 86-90 :)

**Comment by probonopd** [comment]
In helloSystem we are using [Nimbus Sans](https://github.com/helloSystem/hello/issues/18) 10 from https://github.com/ArtifexSoftware/urw-base35-fonts/, better known to the world under the name "Helvetica".
