### ISSUE TITLE
airyx can has an orgs of github?

### ISSUE THREAD

**Issue by cnmade** [mszoek/airyx#240]
currently airyx only under your private name sub project, how about upgrade it to orgnization project.
and let other who want to contribute to join and practice.
Self project can be delete anytime, is it longer enough?

but if it a community driven project, may it a bit longer live?

**Comment by mszoek** [comment]
You mean like this one? :)
https://github.com/airyxos/airyx/tree/main

Contributions are totally welcome...

**Comment by cnmade** [comment]
yes, i can see that project, i see it only allow pull request, but not accept bug report, so i am a bit confuse...
what's the main purpose ?

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As I understand things, we're still in the middle of migrating over to that organization.  That'll also need a rename to match the project's announced/in-progress move to using 'ravynOS.'

**Comment by mszoek** [comment]
Yes, what RandomDSDevel said. There's a project name change in progress and we'll move everything over to an organization once that happens. I'm also working to set up a legal entity (corporation) to own the project's intellectual property so it's not all tied to me.

But... you should still be able to submit bug reports and pull requests to that org and project today. If not, something is wrong.

**Comment by cnmade** [comment]
understand, let this issue close, i have no more question about it.
