### ISSUE TITLE
Up arrow key misinterpreted as a shortcut for Screenshot

### ISSUE THREAD

**Issue by grahamperrin** [mszoek/airyx#50]
Installed from `Helium_0.2.1-F12.2_h0.5.0-amd64.iso`

https://user-images.githubusercontent.com/192271/119236221-22b35580-bb2e-11eb-9546-9759f8001808.mp4

**Comment by mszoek** [comment]
Interesting... it must be mapped to the same as Print or Ctrl-Shift-3 (probably Print) by the keyboard layout.

**Comment by probonopd** [comment]
I encountered this "Up arrow key misinterpreted as a shortcut for Screenshot" error on FreeBSD/helloSystem earlier but I was never able to find out what was causing it and how to resolve it. I think current helloSystem versions don't suffer from it but don't ask me why ;-/

**Comment by mszoek** [comment]
Maybe the fix is in the 13.0 base or package set? It is thankfully easy to work around by removing the shortcut.

**Comment by grahamperrin** [comment]
Thanks, 

> removing the shortcut.

– which one?

**Comment by mszoek** [comment]
> Thanks,
> 
> > removing the shortcut.
> 
> – which one?

I'm not sure. I suspect the Print one, but the issue is not happening for me.
