### ISSUE TITLE
Shared object "libAppKit.so" not found, required by "CocoaDemo"

### ISSUE THREAD

**Issue by probonopd** [mszoek/airyx#52]
Airyx_0.2.2-F12.2_h0.5.0-amd64.iso

![image](https://user-images.githubusercontent.com/2480569/119269538-b7c65500-bbe7-11eb-9bad-7dccf318a72e.png)

Having `launch` show this type of messages was maybe not the worst idea after all ;-)

**Comment by mszoek** [comment]
Ohhhh... I know what that is. I have been using CocoaDemo as the testbed for DBusKit.framework and its RPATHs probably still point into `/Users/zoe/` for a couple of frameworks :) I must have committed that accidentally with the renaming. I'll fix it in the next build.

Nice catch.

**Comment by probonopd** [comment]
Also looks like the Dock doesn't follow symlinks correctly, hence the wrong icon. Opened a ticket: https://github.com/helloSystem/Dock/issues/17
