### ISSUE TITLE
Rebase onto FreeBSD 13.0-RELEASE

### ISSUE THREAD

**Issue by mszoek** [mszoek/airyx#53]

**Comment by probonopd** [comment]
Relevant showstoppers for helloSystem to switch to 13: https://github.com/helloSystem/ISO/issues/198

**Comment by grahamperrin** [comment]
Of possible interest: 

https://github.com/freebsd/poudriere/pull/921

https://github.com/freebsd/poudriere/wiki/poudriere-image.8-devel options etc..

https://github.com/mszoek/airyx/issues/79#issue-962202302

> … video drivers, …

Via <https://old.reddit.com/r/freebsd/comments/pq3lku/technology_roadmap/>: 

[Technology Roadmap | FreeBSD Foundation](https://freebsdfoundation.org/blog/technology-roadmap/) (2021-09-17) 

> … per-release repositories have been proposed. Release-specific overlays could be used to, e.g., offer DRM packages simultaneously for 13.0 and 13.1 while both point releases are supported. …

**Comment by mszoek** [comment]
Updated airyx base to stable/13 branch. Now tracking on airyx/13.
