### ISSUE TITLE
ld-elf.so.1: Shared object "libAppKit.so" not found, required by "CocoaDemo"

### ISSUE THREAD

**Issue by carlosrca** [mszoek/airyx#57]
Thanks for starting this project, **excellent** (helloSystem too) 👍. I wanted to try CocoaDemo but I got the next error:
`ld-elf.so.1: Shared object "libAppKit.so" not found, required by "CocoaDemo"`
Do I need to do something before running the demo?

Thanks!

_Note: Running inside Gnome Boxes v40._

Greetings!!!

![airyx_system](https://user-images.githubusercontent.com/12618041/120253121-2c366f00-c24c-11eb-8af6-53f7deda9c26.png)

**Comment by probonopd** [comment]
Duplicate of https://github.com/mszoek/airyx/issues/52

**Comment by carlosrca** [comment]
Thank you. I didn't notice issue #52. I'll close current issue.
