### ISSUE TITLE
tpm-emulator installs /usr/var/db/tpm instead of /var/db/tpm

### ISSUE THREAD

**Issue by mszoek** [mszoek/airyx#62]

**Comment by probonopd** [comment]
Isn't tpm one of those technologies that work against, not for, the user? Like, for implementing DRM schemes? For me, not needing TPM is a great advantage of open source operating systems. Hence I would like to see tpm-emulator not to be shipped with airyx.

**Comment by mszoek** [comment]
Like any technology, whether TPM is good or bad depends how you use it :) This pkg is only included in Airyx because it was a dependency of something that I built (probably in KDE, possibly a keychain). I haven't done much tuning of build options yet to reduce dependencies - and it's unlikely I'm going with full KDE in the end so this will probably go away.

That said, TPM can be used to hold e.g. disk encryption keys or the master password to your keystore/password manager so that it can be automatically unlocked by biometrics. It's the technology behind stuff like TouchID (Apple calls it a "secure enclave") and Windows Hello. So, not all bad.
