### ISSUE TITLE
Adjust furybsd-* overlays to use /usr and /etc, not /usr/local

### ISSUE THREAD

**Issue by mszoek** [mszoek/airyx#63]

**Comment by probonopd** [comment]
Just out of curiosity, wouldn't you achieve your goal _much_ easier by having a symlink from `/usr/local/etc` to `/etc`, and from `/usr/local/bin` to `/usr/bin, etc., before installing FreeBSD?`

**Comment by mszoek** [comment]
No, because then end-user additions would also end up in the system global directories. I would have to remove the symlinks to prevent that, and removing them would break packages that had their files installed into /etc and /usr (since they are built to actually look in /usr/local).
