### ISSUE TITLE
Add /usr/libdata/ldconfig to the ld-elf paths

### ISSUE THREAD

**Issue by mszoek** [mszoek/airyx#67]

**Comment by probonopd** [comment]
What is the motivation behind this? With changes like this (and the `/usr/local` move) airyx is decreasing compatiblity with plain FreeBSD?

**Comment by mszoek** [comment]
This doesn't decrease compatibility. The path `/usr/local/libdata/ldconfig` is already in the paths searched for linker config files; this patch would just add `/usr/libdata/ldconfig` as well because that's where I've put base OS stuff in Airyx.

I think this is an area where we don't agree... being fully compatible with FreeBSD isn't one of my goals. I do plan to maintain as much compatibility as possible (e.g. I'm not moving everything to use Mach-O or using the xnu kernel) and it should still be possible to use most packages straight out of the FreeBSD repos once I'm done. But that's not the primary goal.

Airyx is not a "layer on top" or a variant or whatever. It is meant to be compatible more with macOS than with FreeBSD, and a full engineered OS that just happens to be built with FreeBSD among other components. The move of everything "base OS" out of /usr/local is because of that philosophy - local is for stuff the end user installs.
