### ISSUE TITLE
Logo/Branding

### ISSUE THREAD

**Issue by llui85** [mszoek/airyx#84]
I've tried designing a logo for this project, as you can see below. What are your thoughts on it? I'll upload the SVGs and original files if you want to use this.

_All images in this issue uploaded by me are licensed under [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)._

| Images | 
|- |
| Main Logo |
| ![Main Logo loading...](https://user-images.githubusercontent.com/47158068/128584760-7fd23f9a-f00c-4e43-9e18-e80b217768af.png) |
| Lockup (Logo + Text) Variation 1 |
| ![Lockup Variation 1 loading...](https://user-images.githubusercontent.com/47158068/128584786-666f3a2e-e7a5-4724-96f0-7b877af02e24.png) |
| Lockup (Logo + Text) Variation 2 |
| ![Lockup Variation 2 loading...](https://user-images.githubusercontent.com/47158068/128584801-3541db9a-353c-4a02-bec9-139ee1400331.png) |
| Stacked Lockup |
| ![Stacked Lockup loading...](https://user-images.githubusercontent.com/47158068/128584823-a5debe19-5f64-417d-a04f-9ddd901831ed.png) |
| Branding concept |
![Branding concept loading...](https://user-images.githubusercontent.com/47158068/128585119-cd415933-5cb3-46e8-ad75-2e9958115bf9.png)

Best wishes,
**llui85**

**Comment by mszoek** [comment]
Hey, thank you! I like the general look of the second lockup. I have strong opinions about the look & feel so apologies in advance, but...

- I'm kind of in love with the Raleway and Quicksand fonts (both free from googlefonts) that I used on airyx.org. Could you see if either work here?
- This image is (partly) what inspired the name: https://i.pinimg.com/736x/63/bc/18/63bc18a6af4afe785911c9ae035c3e0f--nature-desktop-wallpaper-wallpaper-pc.jpg. I would LOVE if the tree symbolism could be worked in somehow!
- I'm not sure about the colors. I like the blue but together they seem a bit close to Walmart or something? I used these ones so far, although they can obviously be changed: #99ccff, #101030, #401040 and #1e90ff

**Comment by llui85** [comment]
Hi there again @mszoek ! Sorry, I've been a bit busy recently, and had to put this work aside for a bit.

Here are few of my ideas, what do you think of them?

![8B1D1AA1-8DF6-4CD1-ADF9-1500FCD01F3B](https://user-images.githubusercontent.com/47158068/131619951-286b592f-bda3-4edf-a65c-92e3f35656b9.png)
![DFC5414C-16FE-4780-9F1C-B5D4696B0AC0](https://user-images.githubusercontent.com/47158068/131619956-4250e7d5-0ad4-4d39-a637-7e53c322fa15.png)
![C2A3617B-BC3C-4975-8284-1E49E79A072F](https://user-images.githubusercontent.com/47158068/131619950-74d5c861-4e6b-4be6-9b0e-479981c95fbf.png)
![F1B87EB9-08D8-4844-A3F9-F31C06AA7C47](https://user-images.githubusercontent.com/47158068/131619931-661e35bb-5985-461b-8e8e-5e607b6277e7.png)

Your designs look good! I like this logo best out of all of them:

![B2EDC072-B01A-4517-90DF-4FCFDE550D06](https://user-images.githubusercontent.com/47158068/131620214-5c82b7bf-179c-4dbe-ba7c-a4fa18f33c26.jpeg)

**Comment by mszoek** [comment]
Hey! These are all cool ideas. Thank you both for working on this!

@nayaabkhan The middle top two-tone design really speaks to me. Could a simplified version of that (just the tree maybe?) work in mono as well for the menu icon?

@llui85 You nailed the overall look on the last two! Love the tightness of the font on the last one. Let's try it in all lowercase as well, and maybe as "airyxOS" as a variation. I'm still deciding on exactly how to brand it. (Suggestions from either of you?)

The palm is super cute too 😃 I had never considered a palm... What about the palm tree says "airyx" to you?

**Comment by nayaabkhan** [comment]
> Could a simplified version of that (just the tree, maybe?) work in mono as well for the menu icon?

Exactly! The two-toned version doesn't scale down too well and loses the details. So instead, we can substitute it for a simplified mono-toned version for tiny sizes. I'll vectorize it to see how it feels.

> I'm still deciding on exactly how to brand it. (Suggestions from either of you?)

I love the `airyxOS` casing. In fact, that's what I tried in my sketches (not sure if that came through clearly, though). Clearly, taking inspiration from how Apple names its OSs. 🥲

**Comment by nayaabkhan** [comment]
Oh, by the way, @mszoek, do you specifically want to go with Raleway or Quicksand? Or would you like to see some alternatives?

**Comment by nayaabkhan** [comment]
| ![Duo-toned Simplified Airyx Blue](https://user-images.githubusercontent.com/234889/131788815-8f37cf61-040a-4d32-bf4d-febbf0a7762a.png) | ![Duo-toned Detailed Airyx Blue](https://user-images.githubusercontent.com/234889/131788804-3b1a94d6-c151-4f46-9ff3-be89b095dea2.png) |
----------|----------
| Duo-toned Simplified Airyx Blue | Duo-toned Detailed Airyx Blue |

| ![Duo-toned Simplified Airyx Sunset](https://user-images.githubusercontent.com/234889/131787652-3f1eeeff-ad6c-4d99-8298-930c3093c0d8.png) | ![Duo-toned Detailed Airyx Sunset](https://user-images.githubusercontent.com/234889/131788152-b52c3034-0bdf-44e9-b37a-213b9d03b1d4.png) |
----------|----------
| Duo-toned Simplified Airyx Sunset | Duo-toned Detailed Airyx Sunset |

| ![Duo-toned Simplified Grayscale](https://user-images.githubusercontent.com/234889/131787657-fa2731d2-cab0-422e-bb4b-4d091dd1fe5d.png) | ![Duo-toned Detailed Grayscale](https://user-images.githubusercontent.com/234889/131788185-278effeb-109c-4689-b7fe-8c3b3df3e5fa.png) |
----------|----------
| Duo-toned Simplified Grayscale | Duo-toned Detailed Grayscale |

| ![Duo-toned Simplified With Name](https://user-images.githubusercontent.com/234889/131788267-6ff25dbe-00da-4d28-af22-ac39de1b5e5a.png) | ![Duo-toned Detailed With Text](https://user-images.githubusercontent.com/234889/131788260-116499cd-4831-4583-ba2f-6359dfd07988.png) |
----------|----------
| Duo-toned Simplified With Name | Duo-toned Detailed With Text |

---

Here's how it came through.

The curves in the detailed tree can be improved given more time but I think they're good enough to get a feel for the time being.

I also love the palm tree idea by @llui85 and I think would be worth a try. I will post it soon, still trying to get the shape right to cut through the circle.

I also tried out a few extra typefaces to see if I can sway you from Raleway/Quicksand 😅.

**Comment by mszoek** [comment]
THESE ARE AWESOME! 💯 🥇 I really like the 2-tone palm design!

I am definitely not married to either Raleway or Quicksand but I do like them. I especially liked the smooth roundness of the shapes in Quicksand and how the 'a' is a simple handwriting-like shape. And the curved 'y' tail.

We use Inter at work and I already have similar colors so I'm going to avoid straying tooooo close to our branding there ;) Satoshi looks nice though - that could definitely work. Within the GUI I'm just using Nimbus Sans (i.e. Helvetica) and Source Code Pro for monospace.

OK - can we try a blue palm with Satoshi in a horizontal and vertical lockup, the palm by itself in black (for the menu bar), and the palm logo without text for the website and splash screen? If that's not too much to ask ;)

**Comment by nayaabkhan** [comment]
Of course, not a problem 😄 I've also attached the SVGs. Feel free to let me know if you need any other format or variation.

[Assets.zip](https://github.com/mszoek/airyx/files/7109222/Assets.zip)

**Comment by mszoek** [comment]
These look great, and will obviously work well on white for a light background. What color would you recommend for dark backgrounds?

Can you do the text in white and black variations as well? I think the color logo with mono text would be really impactful. I love how this is all coming together!

I'll start integrating these into the next build. How do you both want to be credited for this? Maybe something like:.
_Logo designs & artwork by nayaabkhan. Palm concept by llui85._
?? And a link from each name to your portfolio, website, socials, whatever?

**Comment by nayaabkhan** [comment]
Ah, good catch!

> Can you do the text in white and black variations as well? I think the color logo with mono text would be really impactful.

Yep, that's a good idea. The mark would still retain itself and contrast on a dark background with white text (attached). Also, I'll prepare a brand guide with the specs, dos, and don'ts.

> I love how this is all coming together!

😄🙌🏻 I'm glad you like it.

> I'll start integrating these into the next build. How do you both want to be credited for this? Maybe something like:.
> Logo designs & artwork by nayaabkhan. Palm concept by llui85.
?? And a link from each name to your portfolio, website, socials, whatever?

Wow, Thank you so much for that! 😄 I feel so proud to be a part of this project. For the link, I guess my website should be fine: https://nayaabkhan.me.

I've attached the dark theme assets below, let me know if that's how you imagined it:
🧷[Dark Theme Assets.zip](https://github.com/mszoek/airyx/files/7110971/Dark.Theme.Assets.zip)

**Comment by llui85** [comment]
If you want to attribute me for the palm idea you can link to my GitHub profile, but don't worry about it really - @nayaabkhan did most, if not all of the work (and did a much better job than I would have done!)

I'm happy to help with the implementation of the branding on the website if you want - is it open source?

**Comment by nayaabkhan** [comment]
Hey @mszoek, I made the text in the horizontal variation a little larger. So now the mark and the text have almost the same height. I think this looks better, what do you think?

| ![Horizontal](https://user-images.githubusercontent.com/234889/132279706-dd12dc37-5a2a-4a77-9294-57b929adf3c7.png) | ![Horizontal](https://user-images.githubusercontent.com/234889/132279607-868f9337-6cf3-47d3-9ded-31b73f035615.png) |
|:--:|:--:|
| `Before` | `After` |

---
All assets attached in one package:
[Airyx Logo Assets.zip](https://github.com/mszoek/airyx/files/7118669/Airyx.Logo.Assets.zip)

**Comment by mszoek** [comment]
> Hey @mszoek, I made the text in the horizontal variation a little larger. So now the mark and the text have almost the same height. I think this looks better, what do you think?

Absolutely! It looks great. Thanks :)

**Comment by mszoek** [comment]
> If you want to attribute me for the palm idea you can link to my GitHub profile, but don't worry about it really - @nayaabkhan did most, if not all of the work (and did a much better job than I would have done!)
> 
> I'm happy to help with the implementation of the branding on the website if you want - is it open source?

That would be awesome. The website could definitely use attention! I threw it together pretty quickly. It is not currently open but I can give you access. I just need to split it to a separate repo first.

**Comment by mszoek** [comment]
Check it out, guys - it looks awesome :)

![image](https://user-images.githubusercontent.com/60144291/133182297-3692b192-0f63-4e2c-9432-91029754e974.png)

**Comment by nayaabkhan** [comment]
Looks great! Isn't that aliasing too much? Or is it due to zooming in?

**Comment by mszoek** [comment]
> Looks great! Isn't that aliasing too much? Or is it due to zooming in?

I think just from the screenshot & zooming. I used an SVG in the menu so it should scale nicely. (Not that anyone can resize the menus! 😁)

**Comment by mszoek** [comment]
> > If you want to attribute me for the palm idea you can link to my GitHub profile, but don't worry about it really - @nayaabkhan did most, if not all of the work (and did a much better job than I would have done!)
> > I'm happy to help with the implementation of the branding on the website if you want - is it open source?
> 
> That would be awesome. The website could definitely use attention! I threw it together pretty quickly. It is not currently open but I can give you access. I just need to split it to a separate repo first.

Hi @llui85! If you are still interested in helping re-brand and clean up the website, I've made it a public repo here: https://github.com/airyxos/website. PRs would be very much appreciated :)
