### ISSUE TITLE
Pages at the web site

### ISSUE THREAD

**Issue by grahamperrin** [mszoek/airyx#86]
Please, can you have the site make more traditional use of pages?

Earlier today I referred someone to <https://airyx.org/#General>, later I realised that `#General` works only if preceded by a click on the relevant part of the **Go** panel.

**Comment by mszoek** [comment]
yes, I can... sorry about that. Was trying to get some content up quickly due to the uh.. sudden rise in interest ;) and without copy/pasting too much.

**Comment by grahamperrin** [comment]
:-)

**Comment by mszoek** [comment]
Done! All pages are static again with real URLs :)
