### ISSUE TITLE
Why not fish as default shell?

### ISSUE THREAD

**Issue by wesley974** [mszoek/airyx#89]
This is more friendly than zsh.

**Comment by mszoek** [comment]
The default shell is `zsh` for consistency with macOS. I don't plan to change that.
Nothing prevents a user from installing `fish` or changing their shell, though. And perhaps we could ship it by default and make it easy to choose when adding a new user.

**Comment by gaetgu** [comment]
While fish is more friendly (and imho better than) zsh, it has several issues that make it undesirable for making it the new out-of-box shell. The biggest of these is the fact that it is **not** POSIX compliant. There *are* plugins such as `bax` that allow running of POSIX scripts, but for new users keeping ZSH is a much better choice.
