### ISSUE TITLE
What does it take to use xcode

### ISSUE THREAD

**Issue by impetus1** [mszoek/airyx#92]
I realize I cannot use macos binaries however, can you virtualize the docker version of xcode (also on github)? 
I ask since I see no reason a bsd cannot use docker's xcode.

**Comment by mszoek** [comment]
If you are looking at running something like [Docker-OSX](https://github.com/sickcodes/Docker-OSX), that's a full-on macOS image running Xcode inside a Docker container. I assume it would work if you can run Docker, but the output of Xcode will not be compatible with Airyx - it will build normal macOS binaries.

You could use Xcode to edit code and build UIs (NIBs) which can then be compiled on Airyx. It would be great to find or write some kind of tool that translates Xcode project files into BSD Makefiles to make this easier.
